[package]
name = "git-alias-prettifier"
version = "0.1.0"
authors = ["Casper Verhaar <casper.verhaar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
